%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.0.2

-ifndef(example_pb).
-define(example_pb, true).

-define(example_pb_gpb_version, "4.0.2").

-ifndef('HELLOWORLD_PB_H').
-define('HELLOWORLD_PB_H', true).
-record('HelloWorld',
        {message_id             :: non_neg_integer(), % = 1, 32 bits
         content                :: iodata() | undefined % = 2
        }).
-endif.

-endif.
